import CardRow from "components/Global/CardRow/CardRow";
import HomeCollections from "components/Home/HomeCollections/HomeCollections";
import MainSlider from "components/Home/MainSlider/MainSlider";
import Head from "next/head";
import { IProductCard } from "components/Global/ProductCard/ProductCard";

const fakeProducts: IProductCard[] = [
	{
		imageUrl: "/image/sliderImage.jpg",
		name: "گوشواره های جذاب",
		weight: "۴.۴ گرم",
		percent: 25,
		id: "23452354",
		prevPrice: "4,900,000 تومان",
		currentPrice: "4,590,000 تومان",
	},
	{
		imageUrl: "/image/sliderImage.jpg",
		name: "گوشواره های جذاب",
		weight: "۴.۴ گرم",
		percent: 25,
		id: "23452365",
		prevPrice: "4,900,000 تومان",
		currentPrice: "4,590,000 تومان",
	},
	{
		imageUrl: "/image/sliderImage.jpg",
		name: "گوشواره های جذاب",
		weight: "۴.۴ گرم",
		percent: 25,
		id: "23789354",
		prevPrice: "4,900,000 تومان",
		currentPrice: "4,590,000 تومان",
	},
	{
		imageUrl: "/image/sliderImage.jpg",
		name: "گوشواره های جذاب",
		weight: "۴.۴ گرم",
		percent: 25,
		id: "2349-0",
		prevPrice: "4,900,000 تومان",
		currentPrice: "4,590,000 تومان",
	},
	{
		imageUrl: "/image/sliderImage.jpg",
		name: "گوشواره های جذاب",
		weight: "۴.۴ گرم",
		percent: 25,
		id: "25644",
		prevPrice: "4,900,000 تومان",
		currentPrice: "4,590,000 تومان",
	},
	{
		imageUrl: "/image/sliderImage.jpg",
		name: "گوشواره های جذاب",
		weight: "۴.۴ گرم",
		percent: 25,
		id: "23434665",
		prevPrice: "4,900,000 تومان",
		currentPrice: "4,590,000 تومان",
	},
];

export default function Home() {
	return (
		<>
			<Head>
				{/* <title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<main>
				<MainSlider />
				<HomeCollections />
				<CardRow
					name="شگفت انگیز ها"
					allUrl="/"
					products={fakeProducts}
				/>
				<CardRow
					name="جدیدترین کالکشن محصولات"
					allUrl="/"
					products={fakeProducts}
				/>
			</main>

			<footer></footer>
		</>
	);
}
